# Generated by Django 6.0.4 on 2026-04-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Name of person responsible', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist Task',
                'verbose_name_plural': 'Checklist Tasks',
                'ordering': ['completed', 'due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('total_rooms_booked', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('medic', 'Medic'), ('manager', 'Team Manager'), ('coordinator', 'Coordinator'), ('photographer', 'Photographer'), ('other', 'Other')], default='other', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Support Staff',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_identifier', models.CharField(help_text='Room number or name, e.g. 101 or "Blue Room"', max_length=50)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('triple', 'Triple'), ('family', 'Family')], default='twin', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('notes', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='relay.hotel')),
            ],
            options={
                'ordering': ['hotel', 'room_identifier'],
                'unique_together': {('hotel', 'room_identifier')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2')], default=1)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance in kilometres', max_digits=6)),
                ('is_mountain', models.BooleanField(default=False, help_text='Tick if this is a mountain stage')),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, help_text='Scheduled start time of the stage', null=True)),
                ('athlete_report_time', models.TimeField(blank=True, help_text='When the athlete must be at the start', null=True)),
                ('start_location_name', models.CharField(blank=True, max_length=200)),
                ('start_location_address', models.TextField(blank=True, help_text='Full postal address of the start point')),
                ('end_location_name', models.CharField(blank=True, max_length=200)),
                ('end_location_address', models.TextField(blank=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='relay.athlete')),
            ],
            options={
                'ordering': ['stage_number'],
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings', to='relay.athlete')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='relay.hotelroom')),
                ('support_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings', to='relay.supportstaff')),
            ],
            options={
                'ordering': ['room'],
            },
        ),
    ]
