# Generated by Django 6.0.4 on 2026-04-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='urn',
            field=models.CharField(blank=True, max_length=50, verbose_name='URN'),
        ),
    ]
