# Generated by Django 6.0.4 on 2026-04-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_athlete_urn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='distance_miles',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Distance in miles', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Distance in kilometres (auto-calculated)', max_digits=6),
        ),
    ]
