# Generated by Django 6.0.4 on 2026-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0003_stage_distance_miles_alter_stage_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='mens_record',
            field=models.CharField(blank=True, help_text="Men's stage record time (e.g., 50:45)", max_length=20),
        ),
        migrations.AddField(
            model_name='stage',
            name='mens_record_year',
            field=models.IntegerField(blank=True, help_text="Year men's record was set", null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='womens_record',
            field=models.CharField(blank=True, help_text="Women's stage record time (e.g., 56:53)", max_length=20),
        ),
        migrations.AddField(
            model_name='stage',
            name='womens_record_year',
            field=models.IntegerField(blank=True, help_text="Year women's record was set", null=True),
        ),
    ]
