# Generated by Django 6.0.4 on 2026-04-28 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0004_stage_mens_record_stage_mens_record_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_contact',
            field=models.ForeignKey(blank=True, help_text='Support staff member assigned as stage contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_stages', to='relay.supportstaff'),
        ),
    ]
