# Generated by Django 6.0.4 on 2026-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0005_stage_stage_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
