# Generated by Django 6.0.4 on 2026-05-04 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0006_athlete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='reserve1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve1_stages', to='relay.athlete', verbose_name='Reserve 1'),
        ),
        migrations.AddField(
            model_name='stage',
            name='reserve2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve2_stages', to='relay.athlete', verbose_name='Reserve 2'),
        ),
        migrations.AddField(
            model_name='stage',
            name='reserve3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve3_stages', to='relay.athlete', verbose_name='Reserve 3'),
        ),
        migrations.AddField(
            model_name='stage',
            name='reserve4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve4_stages', to='relay.athlete', verbose_name='Reserve 4'),
        ),
        migrations.AddField(
            model_name='stage',
            name='reserve5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve5_stages', to='relay.athlete', verbose_name='Reserve 5'),
        ),
        migrations.AddField(
            model_name='stage',
            name='reserve6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve6_stages', to='relay.athlete', verbose_name='Reserve 6'),
        ),
        migrations.AddField(
            model_name='stage',
            name='travel_time_from_swansea',
            field=models.CharField(blank=True, help_text='Estimated travel time from Swansea (e.g., "2 hours 30 mins")', max_length=50),
        ),
    ]
