# Generated by Django 6.0.4 on 2026-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0007_stage_reserve1_stage_reserve2_stage_reserve3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_reserve',
            field=models.BooleanField(default=False, verbose_name='Reserve Runner'),
        ),
    ]
