# Generated by Django 6.0.4 on 2026-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0008_athlete_is_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
