# Generated by Django 6.0.4 on 2026-06-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0009_athlete_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload photo or video', upload_to='relay_media/%Y/%m/')),
                ('title', models.CharField(blank=True, help_text='Optional title', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Optional caption or description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first (use for sorting)')),
                ('athlete', models.ForeignKey(blank=True, help_text='Athlete who uploaded or is featured', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploads', to='relay.athlete')),
                ('stage', models.ForeignKey(blank=True, help_text='Stage this media is from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploads', to='relay.stage')),
            ],
            options={
                'verbose_name': 'Media Upload',
                'verbose_name_plural': 'Media Uploads',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
    ]
