# Generated by Django 6.0.4 on 2026-06-08 09:26

import relay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0010_mediaupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='file',
            field=models.FileField(help_text='Upload photo or video', upload_to=relay.models.media_upload_path),
        ),
    ]
