# Generated by Django 6.0.4 on 2026-06-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0011_alter_mediaupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='media_type',
            field=models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', help_text='Type of media (set automatically during sync)', max_length=10),
        ),
    ]
